export type AssetPriority = "High" | "Medium" | "Low";

export type AssetRow = {
  sl: string;
  productId: string;
  productName: string;
  category: string;
  subCategory: string;
  brand: string;
  model: string;
  unit: string;
  priority: AssetPriority;
  stock: number;
  minStock: number;
  reorder: number;
  price: number;
  vendor: string;
  createdDate: string;
};

export const DEMO_ASSET_ROWS: AssetRow[] = [
  {
    sl: "054",
    productId: "PRD-IT-001",
    productName: "Desktop PC",
    category: "IT Equipment",
    subCategory: "Computer",
    brand: "Dell",
    model: "OptiPlex 7010",
    unit: "Pcs",
    priority: "High",
    stock: 42,
    minStock: 10,
    reorder: 15,
    price: 65000,
    vendor: "TechVision",
    createdDate: "05 Jan 2025",
  },
  {
    sl: "053",
    productId: "PRD-IT-002",
    productName: "Laptop",
    category: "IT Equipment",
    subCategory: "Computer",
    brand: "HP",
    model: "ProBook 450",
    unit: "Pcs",
    priority: "Medium",
    stock: 28,
    minStock: 8,
    reorder: 12,
    price: 82000,
    vendor: "SmartTech",
    createdDate: "07 Jan 2025",
  },
  {
    sl: "052",
    productId: "PRD-IT-003",
    productName: "Monitor",
    category: "IT Equipment",
    subCategory: "Display",
    brand: "LG",
    model: "24MK600",
    unit: "Pcs",
    priority: "High",
    stock: 55,
    minStock: 15,
    reorder: 20,
    price: 18500,
    vendor: "TechVision",
    createdDate: "08 Jan 2025",
  },
  {
    sl: "051",
    productId: "PRD-IT-004",
    productName: "Keyboard",
    category: "IT Equipment",
    subCategory: "Accessories",
    brand: "Logitech",
    model: "K120",
    unit: "Pcs",
    priority: "Low",
    stock: 120,
    minStock: 30,
    reorder: 40,
    price: 950,
    vendor: "OfficePlus",
    createdDate: "09 Jan 2025",
  },
  {
    sl: "050",
    productId: "PRD-IT-005",
    productName: "Mouse",
    category: "IT Equipment",
    subCategory: "Accessories",
    brand: "Logitech",
    model: "B100",
    unit: "Pcs",
    priority: "Medium",
    stock: 140,
    minStock: 40,
    reorder: 50,
    price: 650,
    vendor: "OfficePlus",
    createdDate: "09 Jan 2025",
  },
  {
    sl: "049",
    productId: "PRD-NW-001",
    productName: "Network Switch",
    category: "Network",
    subCategory: "Switch",
    brand: "Cisco",
    model: "CBS250-24T",
    unit: "Pcs",
    priority: "High",
    stock: 12,
    minStock: 3,
    reorder: 5,
    price: 48000,
    vendor: "NetWorld",
    createdDate: "10 Jan 2025",
  },
  {
    sl: "048",
    productId: "PRD-NW-002",
    productName: "Router",
    category: "Network",
    subCategory: "Router",
    brand: "MikroTik",
    model: "RB4011",
    unit: "Pcs",
    priority: "Medium",
    stock: 9,
    minStock: 2,
    reorder: 4,
    price: 32000,
    vendor: "NetWorld",
    createdDate: "11 Jan 2025",
  },
  {
    sl: "047",
    productId: "PRD-OF-001",
    productName: "Office Chair",
    category: "Office Assets",
    subCategory: "Furniture",
    brand: "Otobi",
    model: "OC-202",
    unit: "Pcs",
    priority: "High",
    stock: 35,
    minStock: 10,
    reorder: 15,
    price: 9500,
    vendor: "FurniWorld",
    createdDate: "12 Jan 2025",
  },
  {
    sl: "046",
    productId: "PRD-OF-002",
    productName: "Printer",
    category: "Office Equipment",
    subCategory: "Printing",
    brand: "Canon",
    model: "LBP2900",
    unit: "Pcs",
    priority: "Low",
    stock: 18,
    minStock: 5,
    reorder: 7,
    price: 21000,
    vendor: "SmartTech",
    createdDate: "13 Jan 2025",
  },
  {
    sl: "045",
    productId: "PRD-NW-003",
    productName: "Firewall",
    category: "Network",
    subCategory: "Security",
    brand: "Fortinet",
    model: "FortiGate 60F",
    unit: "Pcs",
    priority: "Low",
    stock: 4,
    minStock: 1,
    reorder: 2,
    price: 145000,
    vendor: "SecureNet",
    createdDate: "14 Jan 2025",
  },
];
